# C++ Tests using Google Test (Bzlmod)

cc_test(
    name = "Calculator_Test",
    size = "small",
    srcs = ["calculator_test.cpp"],
    deps = [
        "//lib:Calculator",
        "@googletest//:gtest_main",
    ],
)

