# C++ Tests using Google Test

cc_test(
    name = "Calculator_Test",
    size = "small",
    srcs = ["calculator_test.cpp"],
    deps = [
        "//lib:Calculator",
        "@com_google_googletest//:gtest_main",
    ],
)
